title: <p align="center"> Andrew Schell </p>

logo: "/images/picture.png?raw=true"

description:
  <p align="center">
  <a href=""https://github.com/datatalking/pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/andrewschell/">LinkedIn</a> |
  <a href="https://github.com/datatalking">GitHub</a>
  </p>
  
  <p align="justify">
  I've been fortunate to have contributed to many design challenges over the years. From the concrete foundation work for Safeco Baseball Field in Seattle with NBBJ Architects, the F22 Raptor for Northrup Gruman, 777 / 787 redesign for Boeing, the Intel Celeron multi-core processor chip 'Tiger Cage' redesign, and improving user adoption by 62% for Country Financials implementation of Sunguard/Blackrock financial planning software "Planning Station".
  
  I have a BSc in Data Analytics focusing on natural language processing. I'm studying SQL under Professor Jennifer Widom at Stanford Edx, and studying for my MicroMasters at MITx for Statistics and Data Science.
  
  Planning to attend the University of Washington Ph.D. program for Computational Linguistics under Professor Fei Xia and Emily M. Bender.
  <br><br>
  </p>

theme: jekyll-theme-minimal
# TODO update google analytics ID
google_analytics: G-FVCXTYHXBV # Google Analytics tracking ID
plugins:
  - jekyll-remote-theme
